import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@mdxeditor/editor/style.css";
import "./globals.css";
import ClerkProvider from "@/services/clerk/components/ClerkProvider";
import { Toaster } from "sonner";
import { UploadThingSSR } from "@/services/uploadthing/components/UploadThingSSR";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ClerkProvider>
          <Toaster />
          <UploadThingSSR />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
